---
macos_cask_apps:
  - alfred
  - istat-menus
  - docker
  - iterm2
  - bartender
  - dash
  - 1password
  - notion
  - discord
  - slack
  - visual-studio-code
  - sublime-text
  - vnc-viewer
  - coderunner
  - drawio
  - launchcontrol
  - muzzle
  - paw
  - postman
  - snagit
  - spotify
  - vagrant
  - jetbrains-toolbox
  - resilio-sync
  - rectangle
  - monitorcontrol
  - apache-directory-studio
  - utm
  - rar
  - cyberduck
  - mountain-duck
  - microsoft-remote-desktop
