- include: osx.yml
  when: ansible_os_family == "Darwin"
- include: debian.yml
  when: ansible_os_family == "Debian"

- name: Install virtualfish
  pip: name=virtualfish
  become: true

- name: Install Oh-My-Fish
  script: "{{dotfiles_dir}}/scripts/install_omf creates={{home_dir}}/.local/share/omf"
