- include: osx.yml
  when: ansible_os_family == "Darwin"
- include: debian.yml
  when: ansible_os_family == "Debian"
- include: arch.yml
  when: ansible_os_family == "Archlinux"

- name: Install virtualfish
  pip: name=virtualfish
  become: true

- name: Install Oh-My-Fish
  script: "{{dotfiles_dir}}/scripts/install_omf creates={{home_dir}}/.local/share/omf"
  environment:
    dotfiles: "{{dotfiles_dir}}"

- name: Set Fish as preferred shell
  shell: chsh -s `which fish` {{ansible_user_id}}
  become: true
  when: "{{ansible_os_family != 'Darwin' and 'fish' not in ansible_env['SHELL']}}"
