---
- name: Do cross-platform things
  hosts: local
  tasks:
    - name: Make sure common dirs exist
      file:
        path: "{{ home_dir }}/{{ item }}"
        state: directory
        mode: u=rwx
      loop:
        - .config
        - devel
        - devel/contrib
        - bin

    - name: Link custom scripts
      file:
        src: "{{ dotfiles_dir }}/bin/{{ item.name }}"
        dest: "{{ home_dir }}/bin/{{ item.rename | d(item.name) }}"
        state: link
      loop:
        - name: showcert
        - name: awssm
        - name: awssm-multi
        - name: ec2-cache-instances
        - name: ec2-cache-clear
        - name: byobu-grid
        - name: wsl-pbcopy
          rename: pbcopy
          when: "{{ is_wsl }}"
        - name: wsl-pbpaste
          rename: pbpaste
          when: "{{ is_wsl }}"
        - name: cbr2cbz
          when: "{{ work_mode == 'personal' }}"
        - name: git-done
      when: item.when | default(true)

    - include_tasks:
        file: tasks/{{ taskfile }}.yml
        apply:
          tags:
            - "{{ taskfile }}"
      tags: [always]
      loop_control:
        loop_var: taskfile
      loop:
        - git
        - shell-deps
        # - powerline
        #- fish
        - zsh
        - cli-tools
        - vim
        - byobu
        - asdf

    # Recent pip does not like to let you modify system Python packages, which
    # seems pretty sensible. Not sure I need this anyway...
    # - name: Install virtualenvwrapper
    #   become: true
    #   pip:
    #     name: virtualenvwrapper
    #     state: present
    #     executable: "{{ system_pip }}"
