# Macros

[macros.install__trusty]
	prefix = ["sudo", "apt-get", "install", "-y"]

[macros.install__xenial]
	prefix = ["sudo", "apt-get", "install", "-y"]

[macros.addrepo__trusty]
	prefix = ["sudo", "apt-add-repository", "-y"]

[macros.addrepo__xenial]
	prefix = ["sudo", "apt-add-repository", "-y"]

# Installers

[tasks.install_ubuntu]
	deps = [
		"install_python", "install_git", "install_powerline",
		"install_fish",	"install_sublime3", "install_atom",
		"install_synapse", "install_chrome"
	]
	cmds = [
		["@install", "xmonad", "vim", "htop", "httpie", "aptitude", 
		"gnome-session-flashback", "terminator"]
	]

[tasks.install_ubuntu__xenial]
	deps = ["install_ubuntu__"]
	cmds = [["@install", "emacs"]]

[tasks.install_python__trusty]
	rejects = [["which", "pip"]]
	cmds = [["@install", "python-pip"]]

[tasks.install_python__xenial]
	deps = ["install_python__trusty"]

[tasks.install_sublime3__trusty]
	rejects = [["which", "subl"]]
	cmds = [["sudo", "${HM_SRC}/sublime-installer/st3install"]]

[tasks.install_sublime3__xenial]
	deps = ["install_sublime3__trusty"]

[tasks.install_atom__trusty]
	rejects = [["which", "atom"]]
	cmds = [
		["@addrepo", "ppa:webupd8team/atom"],
		["sudo", "apt-get", "update"],
		["@install", "atom"]
	]

[tasks.install_atom__xenial]
	deps = ["install_atom__trusty"]

[tasks.install_fish_shell__trusty]
	rejects = [["which", "fish"]]
	deps = ["fish"]
	cmds = [
		["sudo", "pip", "install", "virtualfish"],
		["@addrepo", "ppa:fish-shell/release-2"],
		["sudo", "apt-get", "update"],
		["@install", "fish", "grc"]
	]

[tasks.install_fish_shell__xenial]
	rejects = [["which", "fish"]]
	deps = ["fish"]
	cmds = [["@install", "fish", "grc"]]

[tasks.install_omf]
	rejects = [["ls", "$HOME/.local/share/omf"]]
	deps = ["install_fish_shell", "fish"]
	cmds = [["${HM_SRC}/scripts/install_omf"]]

[tasks.install_fish]
	deps = ["install_fish_shell", "install_omf"]

[tasks.install_git]
	rejects = [["which", "git"]]
	deps = ["git"]
	cmds = [["@install", "git"]]

[tasks.install_synapse__trusty]
	rejects = [["which", "synapse"]]
	cmds = [
		["@addrepo", "ppa:synapse-core/ppa"],
		["sudo", "apt-get", "update"],
		["@install", "synapse"]
	]

[tasks.install_synapse__xenial]
	rejects = [["which", "synapse"]]
	cmds = [["@install", "synapse"]]

[tasks.install_chrome__trusty]
	rejects = [["which", "google-chrome"]]
	cmds = [["${HM_SRC}/scripts/install_chrome"]]

[tasks.install_chrome__xenial]
	rejects = [["which", "google-chrome"]]
	deps = ["install_chrome__trusty"]

[tasks.install_powerline]
	rejects = [["which", "powerline"]]
	cmds = [
		["pip", "install", "--user", "powerline-status"],
		["pip", "install", "--user", "git+git://github.com/powerline/powerline"]
	]

[tasks.install_powerline__trusty]
	rejects = [["ls", "$HOME/.fonts/PowerlineSymbols.otf"]]
	deps = ["install_powerline__"]
	cmds = [
		["wget", "https://github.com/powerline/powerline/raw/develop/font/PowerlineSymbols.otf"],
		["wget", "https://github.com/powerline/powerline/raw/develop/font/10-powerline-symbols.conf"],
		["mkdir", "-p", "$HOME/.fonts"],
		["mv", "-f", "PowerlineSymbols.otf", "$HOME/.fonts/"],
		["fc-cache", "-vf", "$HOME/.fonts/"],
		["mkdir", "-p", "$HOME/.config/fontconfig/conf.d"],
		["mv", "-f", "10-powerline-symbols.conf", "$HOME/.config/fontconfig/conf.d/"]
	]

[tasks.install_powerline__xenial]
	deps = ["install_powerline__trusty"]

[tasks.install_pycharm__ubuntu]
	cmds = [["${HM_SRC}/scripts/install_jetbrains_ide", "pycharm", "2016.1.3"]]

[tasks.install_pycharm__trusty]
	deps = ["install_pycharm__ubuntu"]

[tasks.install_pycharm__xenial]
	deps = ["install_pycharm__ubuntu"]

[tasks.install_idea__ubuntu]
	cmds = [["${HM_SRC}/scripts/install_jetbrains_ide", "idea", "2016.1.2b"]]

[tasks.install_idea__trusty]
	deps = ["install_idea__ubuntu"]

[tasks.install_idea__xenial]
	deps = ["install_idea__ubuntu"]

[tasks.install_phpstorm__ubuntu]
	cmds = [["${HM_SRC}/scripts/install_jetbrains_ide", "phpstorm", "2016.1.1"]]

[tasks.install_phpstorm__trusty]
	deps = ["install_phpstorm__ubuntu"]

[tasks.install_phpstorm__xenial]
	deps = ["install_phpstorm__ubuntu"]

[tasks.install_datagrip__ubuntu]
	cmds = [["${HM_SRC}/scripts/install_jetbrains_ide", "datagrip", "2016.1"]]

[tasks.install_datagrip__trusty]
	deps = ["install_datagrip__ubuntu"]

[tasks.install_datagrip__xenial]
	deps = ["install_datagrip__ubuntu"]

[tasks.install_lastpass__ubuntu]
	cmds = [["${HM_SRC}/scripts/install_lastpass_ubuntu"]]

[tasks.install_lastpass__trusty]
	deps = ["install_lastpass__ubuntu"]

[tasks.install_lastpass__xenial]
	deps = ["install_lastpass__ubuntu"]

# Configurations

[tasks.fish]
	links = [
		[".config/omf"],
		[".grc", "grc"]
	]

[tasks.xmonad]
	links = [
		[".xmonad/xmonad.hs", "xmonad.hs"]
	]

[tasks.git]
	links = [
		[".global_gitignore", "git/global_gitignore"],
		[".gitconfig.common", "git/gitconfig_common"]
	]

[tasks.git_personal]
	deps = ["git"]
	links = [
		[".gitconfig", "git/gitconfig_personal"]
	]

[tasks.git_work]
	deps = ["git"]
	links = [
		[".gitconfig", "git/gitconfig_work"]
	]

[tasks.emacs]
	links = [
		[".emacs.d", "emacs"],
		["bin/emacs"]
	]

[tasks.base]
	links = [
		[".config/systemd"]
	]

[tasks.devbox]
	deps = ["install_pycharm", "install_idea"]

# Config Profiles

[tasks.ubuntu]
	deps = ["install_ubuntu", "base", "fish", "xmonad", "emacs"]
	links = [
		[".config/terminator/config"],
		[".config/synapse/config.json"],
		[".tmux.conf", "tmux.conf"],
		[".byobu", "byobu"]
	]

[tasks.corvus]
	deps = ["ubuntu", "git_personal", "devbox"]

[tasks.miranda]
	deps = ["ubuntu", "git_personal"]

[tasks.luna]
	deps = ["ubuntu", "git_personal"]

[tasks.work]
	deps = ["ubuntu", "git_work"]

[tasks.mimas]
	deps = ["fish", "git_personal", "emacs"]

