[tasks.common]
	links = [
		[".config/fish/config.fish"],
		[".config/omf"],
		[".oh-my-fish"],
		[".xmonad/xmonad.hs", "xmonad.hs"]
	]

[tasks.corvus]
	deps = ["common"]

[tasks.miranda]
	deps = ["common"]

[tasks.work]
	deps = ["common"]