- hosts: local
  roles:
    - common
    - fonts
    - git
    - powerline
    - fish
    - spacemacs
    - sublime-text-3
    - synapse
    - chrome
    - tilda
    - xmonad
    - compton
    - atom
    - resilio-sync
    - spotify
