- name: Playbook deps
  hosts: local
  tasks:
    - name: Set system python
      set_fact:
        system_python: /bin/python
        system_pip: /bin/pip
        _python_pkgs: [python-pip, python-apt]

    - name: Set system python for newer Ubuntu
      set_fact:
        system_python: /usr/bin/python3
        system_pip: /usr/bin/pip3
        _python_pkgs: [python3-pip, python3-apt]
      when:
        - ansible_distribution in ('Ubuntu', 'Pop!_OS')
        - ansible_distribution_version is version('20.04', '>=')

    - name: Install playbook deps via APT
      when: ansible_os_family == 'Debian'
      become: true
      apt:
        name: "{{ _python_pkgs + ['wget', 'unzip', 'fontconfig'] }}"
        state: present

- import_playbook: common.yml

- name: Linux-specific stuff
  hosts: local
  handlers:
    - name: refresh font cache
      command: fc-cache -f -v
  tasks:
    - name: Create fonts dir
      tags: [fonts]
      file: path={{ item }} state=directory
      loop:
        - "{{ home_dir }}/.local"
        - "{{ home_dir }}/.local/share"
        - "{{ home_dir }}/.local/share/fonts"

    - name: Install fonts
      tags: [fonts]
      copy:
        src: "{{ item }}"
        dest: "{{ home_dir }}/.local/share/fonts"
      with_fileglob: fonts/*.ttf
      notify: refresh font cache
