- name: Playbook deps
  hosts: local
  tasks:
    - name: Set system python
      set_fact:
        system_python: /bin/python
        system_pip: /bin/pip
    - name: Install playbook deps via APT
      when: ansible_os_family == 'Debian'
      become: true
      apt:
        name: [python-pip, python-apt, wget]
        state: present

- import_playbook: common.yml

- name: Linux-specific stuff
  hosts: local
  handlers:
    - name: refresh font cache
      command: fc-cache -f -v
  tasks:
    - name: Create fonts dir
      tags: [fonts]
      file: path={{ item }} state=directory
      loop:
        - "{{ home_dir }}/.local"
        - "{{ home_dir }}/.local/share"
        - "{{ home_dir }}/.local/share/fonts"

    - name: Install fonts
      tags: [fonts]
      copy:
        src: "{{ item }}"
        dest: "{{ home_dir }}/.local/share/fonts"
      with_fileglob: fonts/*.ttf
      notify: refresh font cache
