- name: Playbook deps
  hosts: local
  tasks:
    - name: Install playbook deps via APT
      when: ansible_os_family == 'Debian'
      become: true
      apt:
        name: [python-pip, python-apt, wget]
        state: present

- import_playbook: common.yml

- name: Linux-specific stuff
  hosts: local
  tasks: []
