- hosts: local
  roles:
    - role: common
      tags: [common]
    - fonts
    - git
    - powerline
    - fish
    - vim
    - role: zsh
      tags: [zsh]
  post_tasks:
    - name: Install applications via Homebrew Cask
      tags: [apps, cask]
      homebrew_cask: name={{ item }} state=present
      loop:
        - alfred
        - istat-menus
        - docker
        - iterm2
        - bartender
        - dash
        - 1password
        - notion
        - discord
        - slack
        - atom
        - visual-studio-code
        - sublime-text
        - vnc-viewer
        - coderunner
        - drawio
        - launchcontrol
        - muzzle
        - paw
        - postman
        - snagit
        - spotify
        - virtualbox
        - vagrant
        - jetbrains-toolbox
        - resilio-sync
      ignore_errors: true

    - name: Install applications via Homebrew
      tags: [brew]
      homebrew: name={{ item }} state=present
      loop:
        - kubectx
        - rbenv
        - direnv
        - rsync
        - ccat
        - pyenv
        - bat
        - prettyping
        - fd
        - ncdu
        - ack
        - ag
        - jq
        - exa
        - tldr
        - fzf
        - colordiff
        - rs/tap/curlie

    - name: Install i2cssh
      tags: [cssh, i2cssh]
      gem:
        name: i2cssh
        state: present
        user_install: yes
