- name: Playbook deps
  hosts: local
  tasks:
    - name: Install Homebrew deps for rest of playbook
      homebrew: name=wget state=latest

- import_playbook: common.yml

- name: macOS-specific stuff
  hosts: local
  tasks:
    - name: Install applications via Homebrew Cask
      tags: [apps, cask]
      homebrew_cask:
        state: present
        name:
          - adoptopenjdk
          - alfred
          - istat-menus
          - docker
          - iterm2
          - bartender
          - dash
          - 1password
          - notion
          - discord
          - slack
          - atom
          - visual-studio-code
          - sublime-text
          - vnc-viewer
          - coderunner
          - drawio
          - launchcontrol
          - muzzle
          - paw
          - postman
          - snagit
          - spotify
          - virtualbox
          - vagrant
          - jetbrains-toolbox
          - resilio-sync
          - rectangle
          - monitorcontrol
          - apache-directory-studio
      ignore_errors: true

    - name: Install i2cssh
      tags: [cssh, i2cssh]
      gem:
        name: i2cssh
        state: present
        user_install: yes

    - name: Install fonts
      tags: [fonts]
      copy:
        src: "{{ item }}"
        dest: "{{ home_dir }}/Library/Fonts"
      with_fileglob: fonts/*.ttf

