- hosts: local
  roles:
    - common
    - fonts
    - git
    - powerline
    - fish
    # - spacemacs
    - sublime-text-3
    - atom
    - resilio-sync
    - spotify
    - jetbrains-toolbox
    - virtualbox
    - vagrant
    - vim
  post_tasks:
    - name: Install applications via Homebrew Cask
      homebrew_cask: name={{ item }} state=present
      with_items:
        - alfred
        - istat-menus
        - docker
        - iterm2
        - bartender
        - spectacle

    - name: Install applications via Homebrew
      homebrew: name={{ item }} state=present
      with_items:
        - rbenv
        - direnv
        - rsync
        - ccat
        - pyenv
