- hosts: local
  roles:
    - common
    - fonts
    - git
    - powerline
    - fish
    - spacemacs
    - sublime-text-3
    - atom
    - resilio-sync
    - spotify
    - telegram
    - jetbrains-toolbox
    - spectacle
    - bartender
