#!/usr/bin/env sh

no_inventory () {
    echo >&2 "You must specify the workstation type (personal or work)"
    exit 1
}

[ "$#" -eq 1 ] || no_inventory
[ -f "$1" ] || no_inventory

# Change to dir of script.
cd "${0%/*}"

if [ $(uname) = "Linux" ]; then
    platform="linux"
    sudo apt install -y python3-pip python3-virtualenv libffi-dev libssl-dev build-essential
else
    platform="macos"
fi

if [ ! $(command -v virtualenv) ]; then
    echo "Virtualenv not found! Install virtualenv first."
    exit 1
fi

if [ ! -e ./env/bin/python ]; then
    echo "Initializing virtualenv..."
    virtualenv ./env
fi

./env/bin/pip install -r ./requirements.txt
./env/bin/ansible-galaxy install -r ./requirements.yml

if sudo -n true 2>/dev/null; then
    ./env/bin/ansible-playbook -i $1 $platform.yml
else
    ./env/bin/ansible-playbook -i $1 $platform.yml -K
fi
