#!/usr/bin/env bash

no_inventory () {
    echo >&2 "You must specify the workstation type (personal or work)"
    exit 1
}

[ "$#" -eq 1 ] || no_inventory
[ -f "$1" ] || no_inventory

# Change to dir of script.
cd "${0%/*}"

git pull
git submodule update --init --recursive

if [[ `uname` == 'Linux' ]]; then
    if sudo -n true 2>/dev/null; then
        ansible-playbook -i $1 linux.yml
    else
        ansible-playbook -i $1 linux.yml --ask-sudo-pass
    fi
else
    ansible-playbook -i $1 macos.yml
fi
