---
- name: Create .byobu dirs
  file:
    path: "{{ item }}"
    state: directory
    mode: u=rwx
  loop:
    - "{{ home_dir }}/.byobu"
    - "{{ home_dir }}/.byobu/bin"

- name: Symlink byobu config
  file:
    src: "{{ dotfiles_dir }}/byobu/.tmux.conf"
    dest: "{{ home_dir }}/.byobu/.tmux.conf"
    state: link
    force: true

- name: Symlink byobu status scripts
  file:
    src: "{{ dotfiles_dir }}/byobu/bin/{{ item.script }}"
    dest: "{{ home_dir }}/.byobu/bin/{{ item.freq }}_{{ item.script }}"
    state: link
    force: true
  loop:
    - script: status-sync-panes
      freq: '300'
