---
- name: Install powerline
  pip:
    name: powerline-status
    extra_args: --user

- name: Install pre-patched powerline fonts
  script: "{{dotfiles_dir}}/scripts/powerline-fonts-prepatched creates={{home_dir}}/Library/Fonts/Hack-Bold.ttf"
  when: ansible_os_family == "Darwin"

- name: Patch existing fonts for powerline
  script: "{{dotfiles_dir}}/scripts/powerline-fonts creates={{home_dir}}/.fonts/PowerlineSymbols.otf"
  when: ansible_os_family != "Darwin"
