- include: osx.yml
  when: ansible_os_family == "Darwin"
- include: debian.yml
  when: ansible_os_family == "Debian"
- include: arch.yml
  when: ansible_os_family == "Archlinux"

- include: linux.yml
  when: ansible_system == "Linux"


- name: Link spacemacs config directory
  file:
    src: "{{dotfiles_dir}}/spacemacs"
    dest: "{{home_dir}}/.spacemacs.d"
    state: link
    force: yes
