- name: Install git with Homebrew
  homebrew: name={{item}} state=latest
  with_items:
    - git
    - tig
    - fonts
    - powerline
    - fish
    - spacemacs
    - sublime-text-3
    - chrome
    - atom
    - resilio-sync
