#!/bin/bash

local_archive="/tmp/lastpass.tar.bz2"
remote_archive="https://lastpass.com/lplinux.tar.bz2"
installer_path="/tmp/lplinux"

wget -O ${local_archive} ${remote_archive}
tar xjf ${local_archive} -C /tmp
rm ${local_archive}
cd ${installer_path}
./install_lastpass.sh