#!/bin/bash

wget https://github.com/powerline/powerline/raw/develop/font/PowerlineSymbols.otf
wget https://github.com/powerline/powerline/raw/develop/font/10-powerline-symbols.conf

mkdir -p $HOME/.fonts
mv -f PowerlineSymbols.otf $HOME/.fonts/
fc-cache -vf $HOME/.fonts/

mkdir -p $HOME/.config/fontconfig/conf.d
mv -f 10-powerline-symbols.conf $HOME/.config/fontconfig/conf.d/
