#!/bin/bash

# Versions
roman=2.030R-ro
italic=1.050R-it

wget https://github.com/adobe-fonts/source-code-pro/archive/$roman/$italic.zip
unzip $italic.zip
mkdir -p ~/.fonts
mv source-code-pro-$roman-$italic/OTF/*.otf ~/.fonts
rm -r $italic.zip source-code-pro-$roman-$italic
fc-cache -f -v
