- include: osx.yml
  when: ansible_os_family == "Darwin"
- include: debian.yml
  when: ansible_os_family == "Debian"
- include: arch.yml
  when: ansible_os_family == "Archlinux"

- name: Create personal bin directory
  file: path={{home_dir}}/bin state=directory

- name: Link custom scripts
  file:
    src: "{{ dotfiles_dir }}/bin/{{ item }}"
    dest: "{{ home_dir }}/bin/{{ item }}"
    state: link
  loop:
    - showcert

- name: Install common python deps
  pip: name={{item}}
  with_items: "{{common_python_deps}}"
  become: "{{ansible_os_family != 'Darwin'}}"

- name: Make sure common dirs exist
  file:
    path: "{{ home_dir }}/{{ item }}"
    state: directory
  loop:
    - .config
    - devel
    - devel/contrib
