- name: Install packer deps
  pacman: name={{item}} state=latest
  with_items:
    - jshon
  become: true

- name: Get temporary directory
  command: mktemp -d
  register: packer_dir

- name: Download packer
  git:
    repo:  https://aur.archlinux.org/packer.git
    depth: 1
    dest: "{{packer_dir}}"

- name: Build packer
  command: makepkg -mfs --noconfirm chdir={{packer_dir}}

- name: Install packer
  shell: >
    pacman --noconfirm --noprogressbar --needed -U *.pkg.tar.xz
    chdir={{packer_dir}}
  become: true
