#+TITLE: Emacs Configuration
#+STARTUP: indent

* General App Config
** Disable startup screen
#+name: startup
#+BEGIN_SRC emacs-lisp
  (setq inhibit-startup-screen +1)
#+END_SRC
** Disable ctrl-z
#+name: startup
#+BEGIN_SRC emacs-lisp
  (global-unset-key (kbd "C-z"))
#+END_SRC
** Fix OS X key maps
#+name: startup
#+BEGIN_SRC emacs-lisp
  (setq mac-option-modifier 'super )
  (setq mac-command-modifier 'meta )
  (global-set-key [home] 'beginning-of-visual-line)
  (global-set-key [end] 'end-of-visual-line)
#+END_SRC
** Bar cursor
#+name: startup
#+BEGIN_SRC emacs-lisp
  (setq-default cursor-type 'bar)
#+END_SRC
** Hide menu bar
#+name: startup
#+BEGIN_SRC emacs-lisp
  (menu-bar-mode -1)
#+END_SRC
** Hide tool bar in X interface
#+name: startup
#+BEGIN_SRC emacs-lisp
  (tool-bar-mode -1)
#+END_SRC
** Font
#+name: startup
#+BEGIN_SRC emacs-lisp
  (push '(font . "DejaVu Sans Mono-10") default-frame-alist)
#+END_SRC
** Stop the backup file madness
Backups to .emacs.d subfolder.
#+name: startup
#+BEGIN_SRC emacs-lisp
  (setq backup-directory-alist `(("." . "~/.emacs.d/saves")))
  (setq backup-by-copying t)
#+END_SRC

Put autosave files in temporary directory.
#+name: startup
#+BEGIN_SRC emacs-lisp
  (setq auto-save-file-name-transforms `((".*" ,temporary-file-directory t)))
#+END_SRC

No lock files.
#+name: startup
#+BEGIN_SRC emacs-lisp
  (setq create-lockfiles nil)
#+END_SRC
** No scrollbar
#+name: startup
#+BEGIN_SRC emacs-lisp
  (scroll-bar-mode -1)
#+END_SRC
** Powerline

Pretty mode line.
#+name: look-and-feel
#+BEGIN_SRC emacs-lisp
  (use-package powerline
    :ensure t
    :init (powerline-default-theme))
  #+END_SRC
** Helm
Completion framework used when looking for stuff in a lot of places in Emacs.
#+name: interface
#+BEGIN_SRC emacs-lisp
  (use-package helm
    :ensure t
    :diminish helm-mode
    :bind (("M-x" . helm-M-x)
           ("M-y" . helm-show-kill-ring)
           ("C-x b" . helm-mini)
           ("C-x C-b" . helm-buffers-list)
           ("C-x C-f" . helm-find-files)
           ("C-x C-r" . helm-recentf)
           ("C-x c o" . helm-occur)
           ("C-x c s" . helm-swoop))
    :config (progn
              (require 'helm-config)
              (helm-mode 1)
              (add-hook 'eshell-mode-hook
                        (lambda ()
                          (define-key eshell-mode-map (kbd "TAB") 'helm-esh-pcomplete)
                          (define-key eshell-mode-map (kbd "C-c C-l") 'helm-eshell-history)))))
#+END_SRC
** Projectile
Project management.
#+name: interface
#+BEGIN_SRC emacs-lisp
  (use-package helm-projectile
    :ensure t
    :defer t)

  (use-package projectile
    :ensure t
    :config (progn (setq projectile-mode-line
                         '(:eval (format " [%s]" (projectile-project-name))))
                   (require 'helm-projectile)
                   (helm-projectile-on)
                   (projectile-global-mode)))
#+END_SRC
** Workgroups
Save sessions so you don't have to reopen files.
#+name: session
#+BEGIN_SRC emacs-lisp
  (use-package workgroups2
    :ensure t
    :init (workgroups-mode 1))
#+END_SRC
** Window moving
Global keys.
#+name: interface
#+BEGIN_SRC emacs-lisp
  (use-package buffer-move
    :ensure t)
  (global-set-key (kbd "<C-M-S-up>")     'buf-move-up)
  (global-set-key (kbd "<C-M-S-down>")   'buf-move-down)
  (global-set-key (kbd "<C-M-S-left>")   'buf-move-left)
  (global-set-key (kbd "<C-M-S-right>")  'buf-move-right)
#+END_SRC

Org-mode keys (hides C-S-<arrow> default bindings)
#+name: interface
#+BEGIN_SRC emacs-lisp
  (add-hook 'org-mode-hook '(lambda ()
     (local-set-key [C-M-S-up]    'buf-move-up)
     (local-set-key [C-M-S-down]  'buf-move-down)
     (local-set-key [C-M-S-left]  'buf-move-left)
     (local-set-key [C-M-S-right] 'buf-move-right)))
#+END_SRC
** Window switching
#+name: interface
#+BEGIN_SRC emacs-lisp
  (use-package switch-window
    :ensure t
    :init (global-set-key (kbd "C-x o") 'switch-window))
#+END_SRC
** Auto-load elisp files
Any elisp files in =~/.emacs.local.d/= will be auto-loaded.
#+name: autoload
#+BEGIN_SRC emacs-lisp
  (defun my/load-elisp-directory (path)
    (let ((file-pattern "\\.elc?$"))
      (when (file-directory-p path)
        (mapcar (lambda (lisp-file)
                  (load-file lisp-file))
                (directory-files (expand-file-name path) t file-pattern)))))

  (my/load-elisp-directory "~/.emacs.local.d")
#+END_SRC
* Display Tweaks
** Show curly arrows when wrapping a line
From: http://www.emacswiki.org/emacs/VisualLineMode
#+name: look-and-feel
#+BEGIN_SRC emacs-lisp
  (setq visual-line-fringe-indicators '(left-curly-arrow right-curly-arrow))
#+END_SRC
** When using visual line mode, use better indenting too
#+name: look-and-feel
#+BEGIN_SRC emacs-lisp
  (use-package adaptive-wrap
    :ensure t)
  (setq adaptive-wrap-extra-indent 2)

  (add-hook 'visual-line-mode-hook
    (lambda ()
      (adaptive-wrap-prefix-mode (if visual-line-mode 1 -1))
      (diminish 'visual-line-mode)))
#+END_SRC
** Use Visual Line Mode for text modes
#+name: look-and-feel
#+BEGIN_SRC emacs-lisp
  (add-hook 'text-mode-hook 'turn-on-visual-line-mode)
#+END_SRC
** Change active theme
#+name: look-and-feel
#+BEGIN_SRC emacs-lisp
  (defun my/set-theme (theme)
    (interactive "i")
    (let ((theme (or theme
                     (intern
                      (completing-read "Choose a theme" (custom-available-themes))))))
      (mapcar #'disable-theme custom-enabled-themes)
      (load-theme theme t)
      (powerline-reset)))
#+END_SRC
* Org mode config
** Enable shift-selection
Org mode uses S-<arrow> to move things like TODO lines through
states. This conflicts with Emacs' default of letting S-<arrow> start
or expand marked regions. Turning on org support of shift select means
that it will try to compromise and do selection when nothing else
makes sense, and also allow it when a mark is already set.

Unless we set it to 'always, in which case it doesn't compromise, and
just gives up on S-<arrow>.

#+name: behavior
#+BEGIN_SRC emacs-lisp
  (setq org-support-shift-select 'always)
#+END_SRC
** Use Visual Line Mode for org mode
#+name: look-and-feel
#+BEGIN_SRC emacs-lisp
  (add-hook 'org-mode-hook 'turn-on-visual-line-mode)
#+END_SRC
** Dates when todo is done
#+name: behavior
#+BEGIN_SRC emacs-lisp
  (setq org-log-done t)
#+END_SRC
** Use indented mode
This only shows one star on each heading line, and handles the indentation for you. Little cleaner.
#+name: look-and-feel
#+BEGIN_SRC emacs-lisp
  (setq org-startup-indented t)
#+END_SRC
** Stop inserting blank lines around headings
#+name: behavior
#+BEGIN_SRC emacs-lisp
  ;(setq org-blank-before-new-entry nil)
#+END_SRC
** Download images dragged over buffer
#+name: behavior
#+BEGIN_SRC emacs-lisp
  (use-package org-download :ensure t)
#+END_SRC
** Capture
*** Default Directory
Set a default org directory because we need one... but local environment should set in its .emacs.local.d.
#+name: startup
#+BEGIN_SRC emacs-lisp
  (setq org-directory "~/Dropbox/org")
#+END_SRC
*** Templates
#+name: behavior
#+BEGIN_SRC emacs-lisp
  (setq org-capture-templates
      `(("t" "Task" entry (file+headline "" "Tasks")
         "* TODO %?\n  %u\n  %a")
        ("j" "Journal" entry (file+datetree (concat org-directory "/journal.org"))
         "* %?\nEntered on %U\n  %i\n  %a")
        )
      )
#+END_SRC
** Agenda Configuration
#+name: interface
#+BEGIN_SRC emacs-lisp
  (setq org-agenda-start-on-weekday 0)
  (global-set-key "\C-ca" 'org-agenda)
  (setq org-agenda-todo-ignore-scheduled t)
  (setq org-agenda-todo-ignore-deadlines t)
#+END_SRC
** Publish
#+name: behavior
#+BEGIN_SRC emacs-lisp
  ;; Use HTML5 elements.
  (setq org-html-html5-fancy t)

  ;; Ignore timestamps and publish when I say!
  (setq org-publish-use-timestamps-flag nil)

  ;; Default publish style to solarized light.
  (setq org-html-head "<link rel='stylesheet' type='text/css' href='http://thomasf.github.io/solarized-css/solarized-light.min.css' />")
#+END_SRC
** HTMLize
#+name: behavior
#+BEGIN_SRC emacs-lisp
  ;(use-package htmlize
  ;  :ensure t
  ;  :defer t
  ;  :commands (htmlize-region htmlize-buffer htmlize-file))
#+END_SRC
** Babel
*** Support HTTP requests via Babel
#+name: programming
#+BEGIN_SRC emacs-lisp
  (use-package ob-http
    :ensure t)
#+END_SRC
*** Babel Language Eval
Org-babel evaluation will be turned on for the following
languages. Setting ~Confirm Evaluation~ to ~No~ disables the [[http://orgmode.org/manual/Code-evaluation-security.html][security
prompt]] for that language.

#+name: org-babel-languages
| Language     | Alias | Confirm Evaluation? | Description                     |
|--------------+-------+---------------------+---------------------------------|
| emacs-lisp   |       | Yes                 | Emacs Lisp                      |
| graphviz-dot | dot   | No                  | Directed and undirected graphs  |
| gnuplot      |       | No                  | Graphs                          |
| ditaa        |       | No                  | Ascii diagrams                  |
| plantuml     |       | No                  | Flow charts                     |
| mscgen       |       | No                  | Message sequence charts         |
| haskell      |       | Yes                 | A pure, functional language     |
| python       |       | Yes                 | A dynamic, all-purpose language |
| ruby         |       | Yes                 | A dynamic, all-purpose language |
| sh           |       | Yes                 | Shell scripts                   |
| http         |       | No                  | HTTP requests                   |
| sql          |       | No                  | SQL Queries                     |
| elixir       |       | Yes                 | Elixir                          |
| clojure      |       | Yes                 | Clojure                         |

#+name: babel
#+BEGIN_SRC emacs-lisp :noweb yes
  (defvar my/org-babel-evaluated-languages ())
  (defvar my/org-src-lang-modes ())
  (defvar my/org-babel-no-confirm-languages ())

  (defun my/org-confirm-babel-evaluate (lang body)
    (not (member (intern lang) my/org-babel-no-confirm-languages)))

  (let ((language-table (cddr '<<org-babel-languages()>>)))
    (mapcar (lambda (lang-pair)
              (let* ((alias (if (not (string= (cadr lang-pair) "")) (cadr lang-pair)))
                     (lang (intern (car lang-pair)))
                     (lang-or-alias (if alias (intern alias) lang))
                     (confirm (not (string= (cl-caddr lang-pair) "No"))))
                (if alias
                    (add-to-list 'my/org-src-lang-modes (cons alias lang)))
                (if (not confirm)
                    (add-to-list 'my/org-babel-no-confirm-languages lang-or-alias))
                (add-to-list 'my/org-babel-evaluated-languages lang-or-alias)
                lang-or-alias))
            language-table))

  (mapcar (lambda (alias)
            (add-to-list 'org-src-lang-modes alias))
          my/org-src-lang-modes)

  (org-babel-do-load-languages
   'org-babel-load-languages
   (mapcar (lambda (lang)
             (cons lang t))
           my/org-babel-evaluated-languages))

  (setq org-confirm-babel-evaluate 'my/org-confirm-babel-evaluate)
#+END_SRC
* Editing
** Parens
#+name: behavior
#+BEGIN_SRC emacs-lisp
  (show-paren-mode 1)
  (setq show-paren-delay 0)
  ;; (use-package smartparens
  ;;   :ensure t
  ;;   :init (require 'smartparents-config))
  (use-package autopair
    :ensure t
    :init (autopair-global-mode))
#+END_SRC
** Replace selected text on typing
#+name: behavior
#+BEGIN_SRC emacs-lisp
  (delete-selection-mode 1)
#+END_SRC
** Unfill paragraphs
For the time when you want that paragraph in one line.
From: http://www.emacswiki.org/emacs-test/UnfillParagraph
#+name: behavior
#+BEGIN_SRC emacs-lisp
  ;;; Stefan Monnier <foo at acm.org>. It is the opposite of fill-paragraph    
  (defun unfill-paragraph (&optional region)
    "Takes a multi-line paragraph and makes it into a single line of text."
    (interactive (progn (barf-if-buffer-read-only) '(t)))
    (let ((fill-column (point-max)))
      (fill-paragraph nil region)))

  (define-key global-map "\M-Q" 'unfill-paragraph)
#+END_SRC
** Autocomplete via Company
Company mode is a complete-anything framework.
#+name: behavior
#+BEGIN_SRC emacs-lisp
  (use-package company
    :ensure t
    :config (progn
              (add-hook 'prog-mode-hook 'company-mode)

              (bind-key "C-n" #'company-select-next company-active-map)
              (bind-key "C-p" #'company-select-previous company-active-map)))
  (use-package company-quickhelp
    :ensure t
    :init (eval-after-load 'company '(define-key company-active-map (kbd "M-h") #'company-quickhelp-manual-begin))
    :config (company-quickhelp-mode 1))
#+END_SRC
** Smart home
When pressing home, place cursor at non-blank character.
#+name: behavior
#+BEGIN_SRC emacs-lisp
  (defun smart-beginning-of-line ()
    "Move point to first non-whitespace character or beginning-of-line.

  Move point to the first non-whitespace character on this line.
  If point was already at that position, move point to beginning of line."
    (interactive "^")
    (let ((oldpos (point)))
      (back-to-indentation)
      (and (= oldpos (point))
           (beginning-of-line))))

  (global-set-key [home] 'smart-beginning-of-line)
#+END_SRC
* Languages
** PHP
#+name: programming
#+BEGIN_SRC emacs-lisp
  (use-package web-mode
    :ensure t
    :mode "\\.html?$")

  (use-package php-mode
    :ensure t
    :mode (("\\.php$" . php-mode)
           ("\\.inc$" . php-mode))
    :config (add-hook 'php-mode-hook (lambda ()
                                       "Customize PHP indentation"
                                       (c-set-offset 'arglist-cont-nonempty 'c-lineup-arglist)
                                       (c-set-offset 'substatement-open 0)
                                       (c-set-offset 'case-label '+))))
#+END_SRC
** Python
#+name: programming
#+BEGIN_SRC emacs-lisp
  (use-package python-mode
    :ensure t
    :mode "\.py$")
#+END_SRC

Configure jedi and company-mode to provide auto-completion for python.
#+name: programming
#+begin_src emacs-lisp
  (use-package jedi
    :ensure t
    :commands jedi:setup
    :config (progn
              (setq jedi:use-shortcuts t)
              (jedi:install-server)))

  (use-package pungi
    :ensure t
    :commands pungi:setup-jedi
    :init (add-hook #'python-mode-hook
                    (lambda ()
                      (when buffer-file-name
                        #'pungi:setup-jedi))))

  (use-package company-jedi
    :ensure t
    :config (progn
              (defun my/enable-company-jedi ()
                (when buffer-file-name
                  (add-to-list 'company-backends 'company-jedi)))
              (add-hook #'python-mode-hook
                        #'my/enable-company-jedi)))
#+end_src
** YAML
#+name: programming
#+BEGIN_SRC emacs-lisp
  (use-package yaml-mode
    :ensure t
    :mode "\.yml$")
#+END_SRC
** Fish Shell
#+name: programming
#+BEGIN_SRC emacs-lisp
  (use-package fish-mode
    :ensure t
    :mode "\.fish$")
#+END_SRC
** Haskell
Strongly typed, pure functional language.
#+name: programming
#+BEGIN_SRC emacs-lisp
  (use-package haskell-mode
    :ensure t
    :mode "\.hs$")

  (use-package hi2
    :ensure t
    :commands turn-on-hi2
    :init (add-hook 'haskell-mode-hook 'turn-on-hi2))
#+END_SRC
** Erlang
#+name: programming
#+BEGIN_SRC emacs-lisp
  (use-package erlang
    :ensure t
    :mode ("\.[eh]rl$" . erlang-mode)
    :config (add-hook 'erlang-mode-hook
                      (lambda ()
                        (setq inferior-erlang-machine-options '("-sname" "emacs"
                                                                "-hidden")))))
#+END_SRC
** JSON
#+name: programming
#+BEGIN_SRC emacs-lisp
  (use-package json-mode
    :ensure t
    :mode ("\.json$" . json-mode))
#+END_SRC
** Markdown
Human-compatible, plain-text markup language.
#+name: programming
#+BEGIN_SRC emacs-lisp
  (use-package markdown-mode
    :ensure t
    :mode "\\.(md|markdown|mdown)$")
  (setq markdown-command
        "pandoc -c ~/.emacs.d/gfm-pandoc.css --from markdown_github -t html5 --mathjax --highlight-style pygments --standalone")
#+END_SRC
** Elixir
#+name: programming
#+BEGIN_SRC emacs-lisp
  (use-package elixir-mode
    :ensure t
    :mode ("\.exs?$" . elixir-mode))
  (use-package alchemist
    :ensure t)
  (use-package ob-elixir
    :ensure t)
#+END_SRC
** Docker
#+name: programming
#+BEGIN_SRC emacs-lisp
  (use-package dockerfile-mode
    :ensure t
    :mode ("^Dockerfile$" . dockerfile-mode))
#+END_SRC
** Elm
#+name: programming
#+BEGIN_SRC emacs-lisp
  (use-package elm-mode
    :ensure t
    :mode ("\.elm$" . elm-mode)
    :config (progn
              (setq elm-format-on-save t)
              (add-hook 'elm-mode-hook #'elm-oracle-setup-completion)
              (add-to-list 'company-backends 'company-elm)))
#+END_SRC
** Clojure
#+name: programming
#+BEGIN_SRC emacs-lisp
  (use-package clojure-mode
    :ensure t
    :mode (("\\.clj[sx]?$" . clojure-mode)
           ("\\.edn$" . clojure-mode)))
  (use-package elein
    :ensure t)
#+END_SRC

Cider REPL
#+name: programming
#+BEGIN_SRC emacs-lisp
  (use-package cider
    :ensure t
    :commands (cider-jack-in cider)
    :config (setq org-babel-clojure-backend 'cider))
#+END_SRC
** Apache
#+name: programming
#+BEGIN_SRC emacs-lisp
  (use-package apache-mode
    :ensure t)
#+END_SRC
* Misc Features
** Calendar
Basic calendar functionality.
#+name: behavior
#+BEGIN_SRC emacs-lisp
  (use-package calfw
    :ensure t
    :init (require 'calfw-ical))
#+END_SRC

To use ical integration, you need to load an ical file:
#+name: example
#+BEGIN_SRC emacs-lisp
  (cfw:open-ical-calendar "http://www.google.com/cal/.../basic.ics")
#+END_SRC
** Emacs Server
#+name: session
#+BEGIN_SRC emacs-lisp
  (server-start)
#+END_SRC
** Kill emacs via signal
Kill emacs with =kill <pid> -USR1=.
#+name: session
#+BEGIN_SRC emacs-lisp
  (define-key special-event-map (kbd "<sigusr1>")
                  (lambda ()
                    (interactive)
                    (save-buffers-kill-emacs t)))
#+END_SRC
** Reveal.js
#+name: behavior
#+BEGIN_SRC emacs-lisp
  (use-package ox-reveal
    :ensure t)
#+END_SRC
** Magit
Git client for Emacs.
#+name: behavior
#+BEGIN_SRC emacs-lisp
  (use-package magit
    :ensure t
    :commands (magit-init
               magit-status
               magit-diff
               magit-commit)
    :bind (("C-c m s" . magit-status)
           ("C-c m d" . magit-diff)
           ("C-c m c" . magit-commit)
           ("C-c m l l" . magit-log-head)
           ("C-c m l b" . magit-log-buffer-file)
           ("C-c m l r" . magit-reflog-head))
    :config
    (progn
      (defadvice magit-status (around magit-fullscreen activate)
        (window-configuration-to-register :magit-fullscreen)
        ad-do-it
        (delete-other-windows))
    
      (defadvice magit-quit-window (around magit-restore-screen activate)
        ad-do-it
        (jump-to-register :magit-fullscreen))))

  (use-package magit-blame
    :ensure magit
    :commands magit-blame-mode
    :bind ("C-c m b" . magit-blame))
#+END_SRC
** Remote edit as root
Taken from [[http://www.emacswiki.org/TrampMode#toc32][EmacsWiki]]
#+name: behavior
#+BEGIN_SRC emacs-lisp
  (require 'dired)
  (defun sudo-edit-current-file ()
    (interactive)
    (let ((my-file-name) ; fill this with the file to open
          (position))    ; if the file is already open save position
      (if (equal major-mode 'dired-mode) ; test if we are in dired-mode 
          (progn
            (setq my-file-name (dired-get-file-for-visit))
            (find-alternate-file (prepare-tramp-sudo-string my-file-name)))
        (setq my-file-name (buffer-file-name); hopefully anything else is an already opened file
              position (point))
        (find-alternate-file (prepare-tramp-sudo-string my-file-name))
        (goto-char position))))


  (defun prepare-tramp-sudo-string (tempfile)
    (if (file-remote-p tempfile)
        (let ((vec (tramp-dissect-file-name tempfile)))

          (tramp-make-tramp-file-name
           "sudo"
           (tramp-file-name-user nil)
           (tramp-file-name-host vec)
           (tramp-file-name-localname vec)
           (format "ssh:%s@%s|"
                   (tramp-file-name-user vec)
                   (tramp-file-name-host vec))))
      (concat "/sudo:root@localhost:" tempfile)))

  (define-key dired-mode-map [s-return] 'sudo-edit-current-file)
#+END_SRC
* Config Layout
This imports code from the named blocks above. This is done so that
some things happen in a specific order (such as defining hooks before
reloading buffers).
#+BEGIN_SRC emacs-lisp :tangle yes :noweb no-export :exports code
  ;;;; Do not modify this file by hand.  It was automatically generated
  ;;;; from `emacs.org` in the same directory. See that file for more
  ;;;; information.
  ;;;;

  <<startup>>
  <<look-and-feel>>
  <<interface>>
  <<behavior>>
  <<programming>>
  <<babel>>
  <<autoload>>
  <<session>>
#+END_SRC
